version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: 'npx cypress run --env API_KEY_BASE=${API_KEY_BASE},API_KEY_FREETRIAL=${API_KEY_FREETRIAL} --spec "cypress/e2e/weatherAPI.cy.js"'
