version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress-io/run:
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --browser chrome --spec "cypress/e2e/weatherAPI.cy.js"'
